# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TestNet' do

  use_frameworks!


  pod 'TNetWork', :path => '/Users/tuyongjiang/Desktop/TNetWork/TNetWork.podspec'
  target 'TestNetTests' do

  end

  target 'TestNetUITests' do
  
  end

end
